
services:
  - type: web
    name: tabbycat_website
    env: python
    plan: free
    region: oregon
    buildCommand: "./bin/render-compile.sh"
    startCommand: "daphne -b 0.0.0.0 -p $PORT tabbycat.asgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: WEB_CONCURRENCY
        value: 4
      - key: TAB_DIRECTOR_EMAIL
        sync: false
      - key: TIME_ZONE
        sync: false
      - key: ON_RENDER
        value: true
      - key: USING_NGINX
        value: 0 # Not 'false'; is cast
